// Auto-generated imports for API schemas.
// Regenerate by running the schema generation script.

import '@/app/api/admin/check/schema';
import '@/app/api/allowlist/[bountyId]/schema';
import '@/app/api/beta/applications/schema';
import '@/app/api/beta/apply/schema';
import '@/app/api/beta/check/schema';
import '@/app/api/beta/notify/schema';
import '@/app/api/beta/review/schema';
import '@/app/api/bounties/open/schema';
import '@/app/api/bounty/[bountyId]/schema';
import '@/app/api/bounty/create/schema';
import '@/app/api/contract/bounty/[bountyId]/schema';
import '@/app/api/github/callback/schema';
import '@/app/api/github/installations/schema';
import '@/app/api/health/schema';
import '@/app/api/issue/[repoId]/[issueNumber]/schema';
import '@/app/api/network/default/schema';
import '@/app/api/network/env/schema';
import '@/app/api/nonce/schema';
import '@/app/api/oauth/callback/schema';
import '@/app/api/oauth/github/schema';
import '@/app/api/oauth/logout/schema';
import '@/app/api/oauth/user/schema';
import '@/app/api/openapi/schema';
import '@/app/api/registry/schema';
import '@/app/api/resolver/schema';
import '@/app/api/stats/schema';
import '@/app/api/tokens/schema';
import '@/app/api/user/bounties/schema';
import '@/app/api/user/claimed-bounties/schema';
import '@/app/api/user/profile/schema';
import '@/app/api/user/stats/schema';
import '@/app/api/verify-wallet/schema';
import '@/app/api/wallet/[githubId]/schema';
import '@/app/api/wallet/delete/schema';
import '@/app/api/wallet/link/schema';
import '@/app/api/webhooks/github/schema';
