// Auto-generated imports for API schemas.
// Regenerate by running the schema generation script.

import '@/app/(api)/api/admin/check/schema';
import '@/app/(api)/api/allowlist/[bountyId]/schema';
import '@/app/(api)/api/beta/applications/schema';
import '@/app/(api)/api/beta/apply/schema';
import '@/app/(api)/api/beta/check/schema';
import '@/app/(api)/api/beta/notify/schema';
import '@/app/(api)/api/beta/review/schema';
import '@/app/(api)/api/bounties/open/schema';
import '@/app/(api)/api/bounty/[bountyId]/schema';
import '@/app/(api)/api/bounty/create/schema';
import '@/app/(api)/api/contract/bounty/[bountyId]/schema';
import '@/app/(api)/api/github/callback/schema';
import '@/app/(api)/api/github/installations/schema';
import '@/app/(api)/api/health/schema';
import '@/app/(api)/api/issue/[repoId]/[issueNumber]/schema';
import '@/app/(api)/api/network/default/schema';
import '@/app/(api)/api/network/env/schema';
import '@/app/(api)/api/nonce/schema';
import '@/app/(api)/api/oauth/callback/schema';
import '@/app/(api)/api/oauth/github/schema';
import '@/app/(api)/api/oauth/logout/schema';
import '@/app/(api)/api/oauth/user/schema';
import '@/app/(api)/api/openapi/schema';
import '@/app/(api)/api/registry/schema';
import '@/app/(api)/api/resolver/schema';
import '@/app/(api)/api/stats/schema';
import '@/app/(api)/api/tokens/schema';
import '@/app/(api)/api/user/bounties/schema';
import '@/app/(api)/api/user/claimed-bounties/schema';
import '@/app/(api)/api/user/profile/schema';
import '@/app/(api)/api/user/stats/schema';
import '@/app/(api)/api/verify-wallet/schema';
import '@/app/(api)/api/wallet/[githubId]/schema';
import '@/app/(api)/api/wallet/delete/schema';
import '@/app/(api)/api/wallet/link/schema';
import '@/app/(api)/api/webhooks/github/schema';
