import Link from 'next/link';

const API_DOC_URL = 'https://github.com/lucci/bounty/blob/main/docs/reference/api.md';

export default function ApiDocsPage() {
  return (
    <div className="min-h-screen bg-background text-foreground">
      <div className="mx-auto flex w-full max-w-3xl flex-col gap-6 px-4 py-12 sm:px-6 lg:px-8">
        <div>
          <p className="mb-2 text-sm uppercase tracking-[0.35em] text-muted-foreground/70">
            Documentation
          </p>
          <h1 className="text-3xl font-semibold leading-tight">BountyPay API</h1>
          <p className="mt-4 text-base text-muted-foreground">
            API responses are intentionally small and are documented alongside request details in our
            source repo. Use the reference below whenever you need payload shapes, auth requirements,
            or example flows.
          </p>
        </div>

        <div className="rounded-xl border border-border bg-card px-6 py-5 shadow-md">
          <p className="text-sm text-muted-foreground">Primary reference</p>
          <h2 className="text-xl font-semibold">docs/reference/api.md</h2>
          <p className="mt-2 text-muted-foreground">
            The markdown file covers every `/api/*` route, expected authentication, and error shapes.
            It lives in the repo so updates ship with code changes.
          </p>
          <div className="mt-4 flex flex-wrap items-center gap-3">
            <Link
              href={API_DOC_URL}
              target="_blank"
              rel="noreferrer noopener"
              className="inline-flex items-center rounded-full border border-foreground/20 bg-foreground px-4 py-2 text-sm font-medium text-background transition hover:border-foreground/40"
            >
              View on GitHub
            </Link>
            <code className="rounded-md bg-muted px-3 py-1 text-xs text-muted-foreground">
              docs/reference/api.md
            </code>
          </div>
        </div>

        <div className="rounded-xl border border-dashed border-border/70 bg-card/40 px-6 py-5 text-sm text-muted-foreground">
          Looking for machine-readable specs? We removed the autogenerated OpenAPI surface.
          Reference the markdown file above or inspect the route handlers in `app/(api)/api/*`
          when building SDKs.
        </div>
      </div>
    </div>
  );
}

